---
# tasks file for cassandra_dba
- name: Include vars for os family
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Install Cassandra dba packages
  package:
    name: "{{ cassandra_dba_packages }}"
    state: present
