language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --user --requirement requirements.txt
  - pip --version
  - ansible --version
  - molecule --version
  - pytest --version
script:
  - ./travis_run.sh
after_success:
  - codecov # submit coverage
