---
# tasks file for cassandra_medusa
- name: Check default python version
  shell: python --version
  register: mypy

- name: Install version of python if needed
  include_tasks: install_python3.6.yml
  #when: "{{ mypy.stdout is version('3.6', '<') }}"

- name: Ensure virtual env package is installed
  package:
    name: python-virtualenv
    state: present

- name: Ensure /opt/medusa exists
  file:
    path: /opt/medusa
    state: directory

- name: Install cassandra medusa pip packages
  pip:
    name: "{{ medusa_pip_packages }}"
    state: present
    virtualenv: /opt/medusa
    virtualenv_python: "{{ python_exec_path }}"

- name: Ensure /etc/medusa directory exists
  file:
    path: /etc/medusa
    state: directory
    mode: '0755'

- name: Copy medusa.ini to host
  copy:
    src: medusa.ini
    dest: /etc/medusa/medusa.ini
