---
# tasks file for cassandra_config
- name: Copy template cassandra.yaml
  template:
    src: "cassandra.yaml.j2"
    dest: "/etc/cassandra/conf/cassandra.yaml"
    owner: "cassandra"
    group: "cassandra"
    mode: 0751
    backup: "yes"
